### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by Eldritch-Oliver** [Tyler-A/Nintendo-Switch-Photo-Manager#12]
We should come up with a better name than what we have right now... suggestions are needed.

**Comment by Eldritch-Oliver** [comment]
Suggestions:
 - Effervescence
 - Chimerical
 - eliXer
 - Hippogriff
 - Phantasmagorical
 - Resplendent
 - Switcheroo
 - Zephyr

Any of those stand out to you @dmynerd78 ?

**Comment by dmynerd78** [comment]
Chimerical, Switcheroo, and Zephyr sounds cool but I'm unsure if any of those fit the project well. Switcheroo may be the closest for obvious reasons,

**Comment by Eldritch-Oliver** [comment]
I can agree with those, right now I'm thinking we go with Switcheroo as that has "Switch" in the name as well as the meaning of the word is typically used in the sense of "to swap" so it probably fits the best out of what we can think of because #NamingIsHARD.
