### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Eldritch-Oliver** [Tyler-A/Nintendo-Switch-Photo-Manager#4]
How do we want to do the config, with how we're compressing the file do we try to use a `config.py`, or there's the potential of trying to use environment variables.

**Comment by dmynerd78** [comment]
Other options could be a JSON file or having a plain text file with 
KEY=VALUE pairs that get loaded.

**Comment by Eldritch-Oliver** [comment]
I'd rather not use JSON as it's quite strict and doesn't allow comments, though YAML would be a fine substitute for it as it allows comments.
